framework = "bun"

[install]
production = false
frozen = true
registry = "https://registry.npmjs.org"
cache = true

[test]
coverage = true
timeout = 10_000
watch = false

[debug]
enabled = false
breakpoints = true
port = 9229

[runtime]
env = "production"
watch = false
smol = false

[build]
minify = true
sourcemap = true
target = "bun"

[dev]
hot = false
port = 3000 